apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-cache
  name: registry-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-cache
  template:
    metadata:
      labels:
        app: registry-cache
      name: registry-cache
    spec:
      volumes:
      - name: pull-secret
        hostPath:
          path: /opt/registry/pull-secret.json
      - name: certs
        hostPath:
          path: /opt/registry/certs
          type: Directory
      - name: data
        hostPath:
          path: /opt/registry/data
          type: Directory
      restartPolicy: Always
      containers:
      - name: registry-cache
        image: quay.io/mvalledi/registry-cache:dev
        env:
        - name: CLEANER_MAXSIZE
          value: "10G" # Max Size in human redeable size (M, MB, MiB, G, GB, GiB, ...)
        - name: CLEANER_THRESHOLD_PERCENTAGE
          value: "20" # Percentage threshold. If cache takes CLEANER_MAXSIZE+CLEANER_THRESHOLD_PERCENTAGE%, then cleaner cleans
        - name: CLEANER_RUNEVERY_TIME
          value: "30m" # Cleaner check every CLEANER_RUNEVERY_TIME the cache size. In format "1h2m3s"
        ports:
        - name: registry
          containerPort: 8443
          hostPort: 8443
        # - name: registry-metrics
        #   containerPort: 5001
        #   hostPort: 5001
        hostNetwork: true
        volumeMounts:
        - name: pull-secret
          mountPath: /pull-secret.json
        - name: certs
          mountPath: /certs
        - name: data
          mountPath: /var/lib/registry
