version: 0.1
log:
  accesslog:
    disabled: true
  level: warn
  fields:
    service: $REGISTRY
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: false
http:
  addr: :$LISTENPORT
  headers:
    X-Content-Type-Options: [nosniff]
  debug:
    addr: :$LISTENPORTSTATS
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

notifications:
 endpoints:
   - name: logger
     url: http://127.0.0.1:8000?registry=$REGISTRY
     timeout: 1000ms
     threshold: 1
     backoff: 1s
