version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 2h
      interval: 24h
      dryrun: false    
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

notifications:
 endpoints:
   - name: logger
     url: http://127.0.0.1:8000?token=replace-token-name&hook=logger
     timeout: 1000ms
     threshold: 1
     backoff: 1s
